version: '3.8'

volumes:
  mysql:
    driver: local


services:
  app:
    build:
      context: .
      args:
        HTTP_EXPOSE_PORT: ${HTTP_PORT}
    container_name: express_app
    environment:
      HTTP_PORT: ${HTTP_PORT}
      NODE_ENV: ${NODE_ENV} 
      CI_DB_NAME: ${CI_DB_NAME}
      CI_DB_HOST: ${CI_DB_HOST}
      CI_DB_USERNAME: ${CI_DB_USERNAME}
      CI_DB_PASSWORD: ${CI_DB_PASSWORD}    
    depends_on:
      - db
      # - redis
    restart: always
    ports:
      - ${HTTP_PORT}
    networks:
      - express_network

  db:
    image: mysql
    container_name: express_db
    volumes:
      - mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${CI_DB_PASSWORD}
      MYSQL_DATABASE: ${CI_DB_NAME}
      MYSQL_USER: ${CI_DB_USERNAME}
      MYSQL_PASSWORD: ${CI_DB_PASSWORD}
    restart: always
    networks:
      - express_network

  # redis:
  #   image: 'redis:alpine'
  #   container_name: express_redis
  #   command: redis-server --requirepass ${REDIS_PASSWORD}
  #   ports:
  #     - '6380:6379'
  #   volumes:
  #     - ./storage/redis-data:/var/lib/redis
  #   restart: always
  #   networks:
  #     - express_network

  adminer:
    image: adminer
    container_name: express_adminer
    restart: always
    depends_on:
      - db
    environment:
      ADMINER_DESIGN: flat
    ports:
      - '7002:8080'
    networks:
      - express_network

networks:
  express_network:
    driver: bridge
