version: '3.8'

volumes:
  mysql:
    driver: local


services:
  app:
    build:
      context: .
      args:
        HTTP_PORT: ${HTTP_PORT}
    container_name: express_app
    depends_on:
      - db
      # - redis
    restart: always
    # ports:
    #   - '${PORT}'
    # working_dir: /app
    networks:
      - express_network

  db:
    image: mysql
    container_name: express_db
    volumes:
      - mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${CI_DB_PASSWORD}
      MYSQL_DATABASE: ${CI_DB_NAME}
      MYSQL_USER: ${CI_DB_USERNAME}
      MYSQL_PASSWORD: ${CI_DB_PASSWORD}
    restart: always
    # ports:
    #   - '3307:3306'
    networks:
      - express_network

  # redis:
  #   image: 'redis:alpine'
  #   container_name: express_redis
  #   command: redis-server --requirepass ${REDIS_PASSWORD}
  #   ports:
  #     - '6380:6379'
  #   volumes:
  #     - ./storage/redis-data:/var/lib/redis
  #   restart: always
  #   networks:
  #     - express_network

  # adminer:
  #   image: adminer
  #   container_name: express_adminer
  #   restart: always
  #   depends_on:
  #     - db
  #   environment:
  #     ADMINER_DESIGN: flat
  #   ports:
  #     - '8080:8080'
  #   networks:
  #     - express_network

networks:
  express_network:
    driver: bridge
